### ISSUE TITLE
Mobile Pagination Overflow

### ISSUE THREAD

**Issue by mdziubin** [Exanut/schedubuddy-web#13]
# Expected Behavior

Pagination component should fall within the width of the card in mobile layout (narrow width)

# Current Behavior

Pagination component is overflowing to a newline in mobile layout
![image](https://user-images.githubusercontent.com/60676925/126843925-3860c5f8-015e-41dd-9352-7a2c8f8fc501.png)

**Comment by Exanut** [comment]
patched by 058e534 and 155bf48
