### ISSUE TITLE
Change URL param format

### ISSUE THREAD

**Issue by mdziubin** [Exanut/schedubuddy-web#41]
This is a **breaking change** and will require changes to be synchronized with the backend

### Background
Some URL parameters for `/api/v1/gen-schedules` are being fed in an unlabeled format:
`prefs=${[${eveningClassesBit},${onlineClassesBit},${startPref},${consecPref},${resultSize}]}`

### Proposed Change
Change to individually tagged URL params such as:
`&evening={eveningClassesBit}&online={onlineClassesBit}&startPref={startPref}&consecPref={consecPref}&resultSize={resultSize}`

### Reason
Improves code readability and will allow URL building to be handled by [Javascript's URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL)

**Comment by Exanut** [comment]
Backend now supports this format:
`&evening=${eveningClassesBit}&online=${onlineClassesBit}&start=${startPref}&consec=${consecPref}&limit=${resultSize}`.

The old format will still work.

https://github.com/Exanut/schedubuddy-web/commit/d1459604253b061ff3a89789604d8b859b783be9 calls with the new format.
