### ISSUE TITLE
Occupancy Finder Feature Suggestion - Want Feedback

### ISSUE THREAD

**Issue by ShaishavShah04** [Exanut/schedubuddy-web#60]
Here is the front-end I have in mind for the new occupancy finder feature.

![image](https://user-images.githubusercontent.com/38801683/219958319-b6444dcc-cfc8-4c4f-8aec-1db51abe8b57.png)

I'm working on the backend endpoints right now to support this feature. Basically, it's just a quick way to find all the rooms available given a time frame. 

The first filter is for only displaying rooms which have classes scheduled afterwards.

Additionally, the "No Classes Scheduled Today" is for informing the user that there's a high chance of the room being locked.

I've talked about this feature with @Exanut, and he instructed me to get your feedback on all aspects.

**Comment by mdziubin** [comment]
Thanks for the mockup, looks good to me.

1. Results UI will be paginated like the other tabs
2. I'd move the `After Timeframe ` switch to the left form, keep the controls in one spot

That's all stuff for me to handle though. Once your endpoint is implemented, provide me some details on the params+ result formats and I'll start building.

**Comment by AidenKly** [comment]
HELLO!

This is amazing! Thanks for working on and maintaining it!

I would like to suggest the ability to lock certain classes in place and only show full schedule results that have a certain class at a certain time. For example:

I want to take courses A,B,C and D this term. The schedule builder spits out 30+ results. I want to be able to narrow that down after being shown the schedules to _Just the schedules that have class A at 10:00 AM_. 

Thank you so much! This system is amazing and I'm glad that I found it!
